import assert from 'node:assert/strict';
import { buildPreviewErrorHtml } from './src/services/preview-fallback.ts';

const errorHtml = buildPreviewErrorHtml({ projectName: 'Client portal', error: 'Runtime unavailable' });
assert.match(errorHtml, /data-huggy-preview-error="true"/);
assert.match(errorHtml, /Preview indisponible/);
assert.match(errorHtml, /Runtime unavailable/);
assert.doesNotMatch(errorHtml, /Generated by Huggy|Deployable|Add a task|Revenue|25:00|<button/i);

console.log('strict preview error tests passed');
