import assert from 'node:assert/strict';
import {
  GeneratedOutputParseError,
  extractGeneratedJson,
  looksLikeRawGeneratedEnvelope,
  looksLikeStandaloneHtml,
  stripJsonCodeFence,
} from './src/services/generated-output-parser.ts';

const fenced = [
  'Generated by Huggy',
  '```json',
  JSON.stringify({
    summary: 'Updated the primary button color.',
    files: [
      {
        path: 'index.html',
        language: 'html',
        content: '<!doctype html><html><head><title>Todo</title><meta name="description" content="Todo"></head><body><h1>Todo</h1><button>Save</button></body></html>',
      },
    ],
    backendSchema: '',
    tests: [],
  }),
  '```',
].join('\n');

const parsed = extractGeneratedJson(fenced);
assert.equal(parsed.summary, 'Updated the primary button color.');
assert.equal(parsed.files[0].path, 'index.html');
assert.ok(looksLikeRawGeneratedEnvelope(fenced));

assert.equal(stripJsonCodeFence('```json\n{"ok":true}\n```'), '{"ok":true}');
assert.equal(looksLikeStandaloneHtml('<!doctype html><html><body><h1>Demo</h1></body></html>'), true);
assert.equal(extractGeneratedJson('plain assistant prose without files'), null);

const parseError = new GeneratedOutputParseError();
assert.equal(parseError.diagnosticCode, 'MODEL_OUTPUT_PARSE_FAILED');
assert.equal(parseError.statusCode, 502);

console.log('test-generated-output-parser passed');
