export class GeneratedOutputParseError extends Error {
  diagnosticCode = 'MODEL_OUTPUT_PARSE_FAILED';
  statusCode = 502;

  constructor(message = 'Huggy could not safely read the AI output, so the existing app was kept unchanged.') {
    super(message);
    this.name = 'GeneratedOutputParseError';
  }
}

export function stripJsonCodeFence(value: string): string {
  return String(value || '')
    .trim()
    .replace(/^\uFEFF/, '')
    .replace(/^```(?:json|javascript|js)?\s*/i, '')
    .replace(/\s*```$/i, '')
    .trim();
}

function parseJsonCandidate(candidate: string): any | null {
  const clean = stripJsonCodeFence(candidate);
  if (!clean) return null;
  try {
    return JSON.parse(clean);
  } catch {
    return null;
  }
}

function findBalancedObject(value: string): string | null {
  const source = String(value || '');
  let start = -1;
  let depth = 0;
  let inString = false;
  let escape = false;

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    if (start === -1) {
      if (char === '{') {
        start = index;
        depth = 1;
      }
      continue;
    }

    if (escape) {
      escape = false;
      continue;
    }
    if (char === '\\') {
      escape = true;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      continue;
    }
    if (inString) continue;
    if (char === '{') depth += 1;
    if (char === '}') depth -= 1;
    if (depth === 0) return source.slice(start, index + 1);
  }

  return null;
}

export function extractGeneratedJson(value: string): any | null {
  const source = String(value || '').trim();
  if (!source) return null;

  const direct = parseJsonCandidate(source);
  if (direct) return direct;

  const fenceRegex = /```(?:json|javascript|js)?\s*([\s\S]*?)```/gi;
  let match: RegExpExecArray | null;
  while ((match = fenceRegex.exec(source))) {
    const parsed = parseJsonCandidate(match[1] || '');
    if (parsed) return parsed;
  }

  const balanced = findBalancedObject(source);
  if (balanced) {
    const parsed = parseJsonCandidate(balanced);
    if (parsed) return parsed;
  }

  return null;
}

export function looksLikeStandaloneHtml(value: string): boolean {
  const source = String(value || '').trim();
  return /<!doctype\s+html|<html[\s>]/i.test(source) && /<\/html>/i.test(source);
}

export function looksLikeRawGeneratedEnvelope(value: string): boolean {
  const source = String(value || '');
  return /```json[\s\S]*"files"\s*:/i.test(source)
    || /"summary"\s*:[\s\S]*"files"\s*:/i.test(source)
    || /Generated by Huggy[\s\S]*```json/i.test(source);
}
