export type GeneratedRescueAppKind =
  | 'todo'
  | 'timer'
  | 'commerce'
  | 'booking'
  | 'dashboard'
  | 'ai_tool'
  | 'restaurant'
  | 'portfolio'
  | 'generic';

export type GeneratedRescueInput = {
  projectName?: string;
  prompt?: string;
};

function normalizeInput(input: GeneratedRescueInput | string = {}, prompt = ''): Required<GeneratedRescueInput> {
  if (typeof input === 'string') {
    return {
      projectName: input || 'Huggy App',
      prompt: prompt || input || '',
    };
  }
  return {
    projectName: input.projectName || 'Huggy App',
    prompt: input.prompt || input.projectName || '',
  };
}

function sourceText(input: Required<GeneratedRescueInput>) {
  return `${input.projectName} ${input.prompt}`.toLowerCase();
}

function cleanTitle(value = '', fallback = 'Huggy App') {
  const clean = String(value || '').replace(/\s+/g, ' ').trim();
  if (!clean || /^untitled|huggy app$/i.test(clean)) return fallback;
  return clean.slice(0, 90);
}

function cleanSummary(value = '', fallback = 'A responsive web app generated by Huggy.') {
  const clean = String(value || '').replace(/\s+/g, ' ').trim();
  return (clean || fallback).slice(0, 180);
}

function literal(value: string) {
  return JSON.stringify(value);
}

function appConstants(input: Required<GeneratedRescueInput>, fallbackTitle: string, fallbackSummary: string) {
  return [
    `const appTitle = ${literal(cleanTitle(input.projectName, fallbackTitle))};`,
    `const appSummary = ${literal(cleanSummary(input.prompt, fallbackSummary))};`,
    '',
  ];
}

export function inferGeneratedRescueAppKind(input: GeneratedRescueInput | string = {}, prompt = ''): GeneratedRescueAppKind {
  const normalized = normalizeInput(input, prompt);
  const text = sourceText(normalized);
  if (/\b(pomodoro|pomodero|minuteur|timer|countdown|chrono|focus session|short break|long break)\b/.test(text)) return 'timer';
  if (/\b(todo|to-do|to do|task|tasks|tache|taches|checklist|kanban|liste de taches|gestion de taches)\b/.test(text)) return 'todo';
  if (/\b(ecommerce|e-commerce|commerce|shop|store|cart|checkout|product|products|panier|boutique|catalogue|produit|payment|paiement)\b/.test(text)) return 'commerce';
  if (/\b(restaurant|menu|dish|table|chef|local business|business local|cafe|coffee|meal)\b/.test(text)) return 'restaurant';
  if (/\b(booking|reservation|appointment|calendar|slot|rendez-vous|rdv|calendrier|availability)\b/.test(text)) return 'booking';
  if (/\b(dashboard|admin|crm|analytics|metric|kpi|client|invoice|pipeline|portal|erp|backoffice|internal tool)\b/.test(text)) return 'dashboard';
  if (/\b(ai tool|chatbot|assistant|prompt|generator|resume|summarize|rewrite|llm|outil ia|generateur ia)\b/.test(text)) return 'ai_tool';
  if (/\b(portfolio|agency|landing|one page|site vitrine|case study|contact form|personal site|creative)\b/.test(text)) return 'portfolio';
  return 'generic';
}

export function createGeneratedRescueAppTsx(input: GeneratedRescueInput | string = {}, prompt = '') {
  const normalized = normalizeInput(input, prompt);
  const kind = inferGeneratedRescueAppKind(normalized);
  if (kind === 'todo') return todoApp(normalized);
  if (kind === 'timer') return timerApp(normalized);
  if (kind === 'commerce') return commerceApp(normalized);
  if (kind === 'booking') return bookingApp(normalized);
  if (kind === 'dashboard') return dashboardApp(normalized);
  if (kind === 'ai_tool') return aiToolApp(normalized);
  if (kind === 'restaurant') return restaurantApp(normalized);
  if (kind === 'portfolio') return portfolioApp(normalized);
  return genericApp(normalized);
}

function todoApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { FormEvent, useEffect, useMemo, useState } from 'react';",
    "import './index.css';",
    '',
    "type Filter = 'all' | 'active' | 'completed';",
    'type Todo = { id: number; title: string; completed: boolean };',
    "const STORAGE_KEY = 'huggy.generated.todos.v1';",
    ...appConstants(input, 'Todo workspace', 'Add, complete, filter and delete tasks with browser persistence.'),
    'const seedTodos: Todo[] = [',
    "  { id: 1, title: 'Review the first release', completed: true },",
    "  { id: 2, title: 'Test the preview on mobile', completed: false },",
    '];',
    '',
    'function readTodos(): Todo[] {',
    '  try {',
    '    const raw = window.localStorage.getItem(STORAGE_KEY);',
    '    const parsed = raw ? JSON.parse(raw) : null;',
    '    return Array.isArray(parsed) ? parsed : seedTodos;',
    '  } catch {',
    '    return seedTodos;',
    '  }',
    '}',
    '',
    'export default function App() {',
    '  const [todos, setTodos] = useState<Todo[]>(() => readTodos());',
    "  const [title, setTitle] = useState('');",
    "  const [filter, setFilter] = useState<Filter>('all');",
    "  const [feedback, setFeedback] = useState('Ready.');",
    '  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(todos)); }, [todos]);',
    '  const visibleTodos = useMemo(() => todos.filter((todo) => filter === "all" || (filter === "completed" ? todo.completed : !todo.completed)), [todos, filter]);',
    '  const completedCount = todos.filter((todo) => todo.completed).length;',
    '',
    '  function addTodo(event: FormEvent) {',
    '    event.preventDefault();',
    '    const clean = title.trim();',
    "    if (!clean) { setFeedback('Add a task name first.'); return; }",
    '    setTodos((current) => [{ id: Date.now(), title: clean, completed: false }, ...current]);',
    "    setTitle('');",
    "    setFeedback('Task added.');",
    '  }',
    '',
    '  function removeTodo(todo: Todo) {',
    '    if (!window.confirm(`Delete "${todo.title}"?`)) return;',
    '    setTodos((current) => current.filter((item) => item.id !== todo.id));',
    "    setFeedback('Task deleted.');",
    '  }',
    '',
    '  return (',
    '    <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-950 sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8" aria-label="Todo application">',
    '        <p className="mb-3 text-xs font-bold uppercase tracking-[0.22em] text-blue-600">Generated by Huggy</p>',
    '        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">',
    '          <div>',
    '            <h1 className="text-3xl font-bold tracking-tight sm:text-5xl">{appTitle}</h1>',
    '            <p className="mt-3 max-w-xl leading-7 text-slate-600">{appSummary}</p>',
    '          </div>',
    '          <strong className="rounded-full bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700">{completedCount}/{todos.length} done</strong>',
    '        </div>',
    '        <form className="mt-8 grid gap-3 sm:grid-cols-[1fr_auto]" onSubmit={addTodo}>',
    '          <input className="min-h-12 rounded-full border border-slate-200 bg-white px-4 text-slate-950 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Add a task..." aria-label="Task name" />',
    '          <button className="min-h-12 rounded-full bg-slate-950 px-5 font-semibold text-white transition hover:bg-blue-700" type="submit">Add task</button>',
    '        </form>',
    '        <div className="mt-4 flex flex-wrap gap-2" aria-label="Task filters">',
    "          {(['all', 'active', 'completed'] as Filter[]).map((item) => (",
    '            <button key={item} type="button" className={filter === item ? "rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white" : "rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-blue-300"} onClick={() => setFilter(item)}>{item}</button>',
    '          ))}',
    '        </div>',
    '        <p className="mt-4 rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-700" role="status">{feedback}</p>',
    '        <ul className="mt-5 grid gap-3">',
    '          {visibleTodos.length ? visibleTodos.map((todo) => (',
    '            <li className="flex flex-col gap-3 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between" key={todo.id}>',
    '              <label className="flex items-center gap-3">',
    '                <input className="size-5 accent-blue-600" type="checkbox" checked={todo.completed} onChange={() => setTodos((current) => current.map((item) => item.id === todo.id ? { ...item, completed: !item.completed } : item))} />',
    '                <span className={todo.completed ? "text-slate-400 line-through" : "text-slate-900"}>{todo.title}</span>',
    '              </label>',
    '              <button className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-red-200 hover:bg-red-50 hover:text-red-700" type="button" onClick={() => removeTodo(todo)}>Delete</button>',
    '            </li>',
    '          )) : <li className="rounded-2xl border border-dashed border-slate-300 p-6 text-center text-slate-500">No tasks match this filter.</li>}',
    '        </ul>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function timerApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { useEffect, useMemo, useState } from 'react';",
    "import './index.css';",
    '',
    "type Mode = 'focus' | 'short' | 'long';",
    "const modes: Record<Mode, { label: string; seconds: number }> = { focus: { label: 'Focus', seconds: 25 * 60 }, short: { label: 'Short break', seconds: 5 * 60 }, long: { label: 'Long break', seconds: 15 * 60 } };",
    ...appConstants(input, 'Pomodoro timer', 'Run focus sessions, pause, reset and track completed cycles.'),
    'function formatTime(value: number) { return `${Math.floor(value / 60).toString().padStart(2, "0")}:${(value % 60).toString().padStart(2, "0")}`; }',
    '',
    'export default function App() {',
    "  const [mode, setMode] = useState<Mode>('focus');",
    '  const [seconds, setSeconds] = useState(modes.focus.seconds);',
    '  const [isRunning, setIsRunning] = useState(false);',
    '  const [cycles, setCycles] = useState(0);',
    "  const [feedback, setFeedback] = useState('Ready for a focus session.');",
    '  useEffect(() => {',
    '    if (!isRunning) return undefined;',
    '    const timer = window.setInterval(() => {',
    '      setSeconds((value) => {',
    '        if (value <= 1) {',
    '          setIsRunning(false);',
    '          setCycles((count) => count + 1);',
    "          setFeedback('Session complete. Choose the next mode.');",
    '          return modes[mode].seconds;',
    '        }',
    '        return value - 1;',
    '      });',
    '    }, 1000);',
    '    return () => window.clearInterval(timer);',
    '  }, [isRunning, mode]);',
    '  const progress = useMemo(() => Math.round(((modes[mode].seconds - seconds) / modes[mode].seconds) * 100), [mode, seconds]);',
    '  function switchMode(next: Mode) { setMode(next); setSeconds(modes[next].seconds); setIsRunning(false); setFeedback(`${modes[next].label} selected.`); }',
    '  function resetTimer() { setIsRunning(false); setSeconds(modes[mode].seconds); setFeedback("Timer reset."); }',
    '',
    '  return (',
    '    <main className="min-h-screen bg-slate-950 px-4 py-8 text-white sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-3xl rounded-3xl border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur sm:p-8" aria-label="Pomodoro timer">',
    '        <p className="mb-3 text-xs font-bold uppercase tracking-[0.22em] text-blue-300">Generated by Huggy</p>',
    '        <h1 className="text-3xl font-bold tracking-tight sm:text-5xl">{appTitle}</h1>',
    '        <p className="mt-3 text-blue-100">{appSummary}</p>',
    '        <div className="mt-6 rounded-[2rem] border border-white/10 bg-slate-900 p-8 text-center">',
    '          <strong className="block text-7xl font-black tracking-tight sm:text-8xl">{formatTime(seconds)}</strong>',
    '          <span className="mt-2 block text-blue-200">{modes[mode].label}</span>',
    '          <div className="mt-5 h-2 rounded-full bg-white/10"><span className="block h-full rounded-full bg-blue-400" style={{ width: `${progress}%` }} /></div>',
    '        </div>',
    '        <div className="mt-5 flex flex-wrap gap-2">',
    '          {(Object.keys(modes) as Mode[]).map((item) => <button key={item} className={mode === item ? "rounded-full bg-blue-400 px-4 py-2 text-sm font-bold text-slate-950" : "rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-white transition hover:border-blue-300"} type="button" onClick={() => switchMode(item)}>{modes[item].label}</button>)}',
    '        </div>',
    '        <div className="mt-5 grid gap-3 sm:grid-cols-3">',
    '          <button className="rounded-full bg-white px-5 py-3 font-semibold text-slate-950" type="button" onClick={() => { setIsRunning(true); setFeedback("Timer running."); }}>Start</button>',
    '          <button className="rounded-full border border-white/10 px-5 py-3 font-semibold text-white" type="button" onClick={() => { setIsRunning(false); setFeedback("Paused."); }}>Pause</button>',
    '          <button className="rounded-full border border-white/10 px-5 py-3 font-semibold text-white" type="button" onClick={resetTimer}>Reset</button>',
    '        </div>',
    '        <p className="mt-4 rounded-2xl bg-blue-400/10 px-4 py-3 text-sm text-blue-100" role="status">{feedback} Cycles: {cycles}</p>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function commerceApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { useMemo, useState } from 'react';",
    "import './index.css';",
    '',
    'type Product = { id: number; name: string; price: number; variant: string };',
    "const products: Product[] = [{ id: 1, name: 'Studio Backpack', price: 89, variant: 'Black' }, { id: 2, name: 'Launch Hoodie', price: 64, variant: 'Blue' }, { id: 3, name: 'Creator Bottle', price: 28, variant: 'Steel' }];",
    ...appConstants(input, 'Product storefront', 'Browse products, choose variants, update quantity and receive checkout feedback.'),
    '',
    'export default function App() {',
    '  const [cart, setCart] = useState<Product[]>([]);',
    "  const [variant, setVariant] = useState('Black');",
    '  const [quantity, setQuantity] = useState(1);',
    "  const [feedback, setFeedback] = useState('Choose a product to start.');",
    '  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price, 0) * quantity, [cart, quantity]);',
    '  function addToCart(product: Product) { setCart((current) => [{ ...product, variant }, ...current]); setFeedback(`${product.name} added to cart.`); }',
    '  function removeFromCart(product: Product) { setCart((current) => current.filter((item, index) => item.id !== product.id || index !== current.findIndex((match) => match.id === product.id))); setFeedback(`${product.name} removed.`); }',
    '  function checkout() { if (!cart.length) { setFeedback("Your cart is empty."); return; } setFeedback(`Checkout ready for ${cart.length} item(s). Demo payment confirmation created.`); }',
    '',
    '  return (',
    '    <main className="min-h-screen bg-stone-50 px-4 py-8 text-stone-950 sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-6xl">',
    '        <p className="mb-3 text-xs font-bold uppercase tracking-[0.22em] text-blue-600">Generated by Huggy</p>',
    '        <h1 className="text-4xl font-black tracking-tight sm:text-6xl">{appTitle}</h1>',
    '        <p className="mt-3 max-w-2xl text-stone-600">{appSummary}</p>',
    '        <div className="mt-6 flex flex-wrap gap-3">',
    '          <select className="rounded-full border border-stone-200 bg-white px-4 py-3" value={variant} onChange={(event) => setVariant(event.target.value)} aria-label="Variant"><option>Black</option><option>Blue</option><option>Steel</option></select>',
    '          <label className="rounded-full border border-stone-200 bg-white px-4 py-3">Qty <input className="w-14 bg-transparent text-center font-bold" type="number" min="1" value={quantity} onChange={(event) => setQuantity(Math.max(1, Number(event.target.value) || 1))} /></label>',
    '          <button className="rounded-full bg-stone-950 px-5 py-3 font-bold text-white" type="button" onClick={checkout}>Checkout</button>',
    '        </div>',
    '        <div className="mt-8 grid gap-4 md:grid-cols-3">{products.map((product) => <article className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm" key={product.id}><div className="mb-4 h-32 rounded-2xl bg-gradient-to-br from-blue-100 to-stone-200" /><h2 className="text-xl font-bold">{product.name}</h2><p className="text-stone-500">{product.variant} collection</p><strong className="mt-3 block text-2xl">${product.price}</strong><button className="mt-4 w-full rounded-full bg-blue-600 px-4 py-3 font-bold text-white" type="button" onClick={() => addToCart(product)}>Add to cart</button></article>)}</div>',
    '        <aside className="mt-6 rounded-3xl border border-stone-200 bg-white p-5"><h2 className="font-bold">Cart</h2><p className="mt-2 text-stone-600">{cart.length ? `${cart.length} item(s), quantity ${quantity}, total $${total}` : "No items yet."}</p><div className="mt-3 flex flex-wrap gap-2">{cart.map((item, index) => <button className="rounded-full border border-stone-200 px-3 py-2 text-sm" key={`${item.id}-${index}`} type="button" onClick={() => removeFromCart(item)}>Remove {item.name}</button>)}</div><p className="mt-3 rounded-2xl bg-blue-50 px-4 py-3 text-sm text-blue-800" role="status">{feedback}</p></aside>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function bookingApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { FormEvent, useState } from 'react';",
    "import './index.css';",
    '',
    "const slots = ['09:00', '11:30', '14:00', '16:30'];",
    ...appConstants(input, 'Booking app', 'Choose an availability slot, submit details and receive confirmation feedback.'),
    '',
    'export default function App() {',
    "  const [slot, setSlot] = useState('09:00');",
    "  const [name, setName] = useState('');",
    '  const [bookings, setBookings] = useState<string[]>([]);',
    "  const [feedback, setFeedback] = useState('Select a time slot.');",
    '  function submitBooking(event: FormEvent) { event.preventDefault(); if (!name.trim()) { setFeedback("Add your name first."); return; } setBookings((current) => [`${name.trim()} - ${slot}`, ...current]); setName(""); setFeedback(`Booking confirmed for ${slot}.`); }',
    '  return (',
    '    <main className="min-h-screen bg-sky-50 px-4 py-8 text-slate-950 sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-4xl rounded-3xl bg-white p-6 shadow-sm sm:p-8">',
    '        <p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-600">Generated by Huggy</p>',
    '        <h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{appTitle}</h1>',
    '        <p className="mt-3 text-slate-600">{appSummary}</p>',
    '        <div className="mt-6 flex flex-wrap gap-2">{slots.map((item) => <button key={item} className={slot === item ? "rounded-full bg-blue-600 px-4 py-2 font-bold text-white" : "rounded-full border border-slate-200 px-4 py-2 font-bold text-slate-700"} type="button" onClick={() => setSlot(item)}>{item}</button>)}</div>',
    '        <form className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto]" onSubmit={submitBooking}><input className="rounded-full border border-slate-200 px-4 py-3" value={name} onChange={(event) => setName(event.target.value)} placeholder="Customer name" aria-label="Customer name" /><button className="rounded-full bg-slate-950 px-5 py-3 font-bold text-white" type="submit">Book now</button></form>',
    '        <p className="mt-4 rounded-2xl bg-blue-50 px-4 py-3 text-blue-800" role="status">{feedback}</p>',
    '        <ul className="mt-5 grid gap-2">{bookings.length ? bookings.map((item) => <li className="rounded-2xl border border-slate-200 p-3" key={item}>{item}</li>) : <li className="rounded-2xl border border-dashed border-slate-300 p-4 text-slate-500">No bookings yet.</li>}</ul>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function dashboardApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { useMemo, useState } from 'react';",
    "import './index.css';",
    '',
    "const rows = [{ name: 'Acme', status: 'Active', value: 12400 }, { name: 'Nova', status: 'Review', value: 8300 }, { name: 'Orbit', status: 'Active', value: 15600 }];",
    ...appConstants(input, 'Operations dashboard', 'Filter records, inspect metrics and trigger visible operational feedback.'),
    '',
    'export default function App() {',
    "  const [filter, setFilter] = useState('All');",
    "  const [feedback, setFeedback] = useState('Dashboard loaded.');",
    '  const visible = useMemo(() => rows.filter((row) => filter === "All" || row.status === filter), [filter]);',
    '  const total = visible.reduce((sum, row) => sum + row.value, 0);',
    '  return (',
    '    <main className="min-h-screen bg-slate-950 px-4 py-8 text-white sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-6xl">',
    '        <p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-300">Generated by Huggy</p>',
    '        <h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{appTitle}</h1>',
    '        <p className="mt-3 max-w-2xl text-blue-100">{appSummary}</p>',
    '        <div className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-3xl bg-white/10 p-5"><span className="text-blue-200">Revenue</span><strong className="block text-3xl">${total.toLocaleString()}</strong></article><article className="rounded-3xl bg-white/10 p-5"><span className="text-blue-200">Accounts</span><strong className="block text-3xl">{visible.length}</strong></article><article className="rounded-3xl bg-white/10 p-5"><span className="text-blue-200">Health</span><strong className="block text-3xl">98%</strong></article></div>',
    '        <div className="mt-6 flex flex-wrap gap-2">{["All", "Active", "Review"].map((item) => <button key={item} className={filter === item ? "rounded-full bg-blue-400 px-4 py-2 font-bold text-slate-950" : "rounded-full border border-white/10 px-4 py-2 font-bold text-white"} type="button" onClick={() => { setFilter(item); setFeedback(`${item} accounts shown.`); }}>{item}</button>)}</div>',
    '        <div className="mt-5 overflow-hidden rounded-3xl border border-white/10">{visible.map((row) => <div className="grid gap-2 border-b border-white/10 p-4 sm:grid-cols-3" key={row.name}><strong>{row.name}</strong><span>{row.status}</span><span>${row.value.toLocaleString()}</span></div>)}</div>',
    '        <p className="mt-4 rounded-2xl bg-blue-400/10 px-4 py-3 text-blue-100" role="status">{feedback}</p>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function aiToolApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { FormEvent, useState } from 'react';",
    "import './index.css';",
    '',
    ...appConstants(input, 'AI workspace', 'Write a prompt, generate a useful result and keep a small local history.'),
    '',
    'export default function App() {',
    "  const [prompt, setPrompt] = useState('');",
    "  const [result, setResult] = useState('Your generated response will appear here.');",
    '  const [history, setHistory] = useState<string[]>([]);',
    '  function generate(event: FormEvent) { event.preventDefault(); const clean = prompt.trim(); if (!clean) { setResult("Write a prompt first."); return; } const output = `Draft generated for: ${clean}`; setResult(output); setHistory((current) => [output, ...current]); setPrompt(""); }',
    '  return (',
    '    <main className="min-h-screen bg-indigo-50 px-4 py-8 text-slate-950 sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-4xl rounded-3xl bg-white p-6 shadow-sm sm:p-8">',
    '        <p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-600">Generated by Huggy</p>',
    '        <h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{appTitle}</h1>',
    '        <p className="mt-3 text-slate-600">{appSummary}</p>',
    '        <form className="mt-6 grid gap-3" onSubmit={generate}><textarea className="min-h-32 rounded-3xl border border-slate-200 p-4" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Describe what to generate..." aria-label="AI prompt" /><button className="rounded-full bg-slate-950 px-5 py-3 font-bold text-white" type="submit">Generate</button></form>',
    '        <div className="mt-5 rounded-3xl bg-slate-100 p-5"><strong>Result</strong><p className="mt-2 text-slate-700" role="status">{result}</p><button className="mt-4 rounded-full border border-slate-200 bg-white px-4 py-2 font-bold" type="button" onClick={() => navigator.clipboard?.writeText(result)}>Copy result</button></div>',
    '        <ul className="mt-5 grid gap-2">{history.map((item) => <li className="rounded-2xl border border-slate-200 p-3" key={item}>{item}</li>)}</ul>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function restaurantApp(input: Required<GeneratedRescueInput>) {
  return [
    "import { FormEvent, useMemo, useState } from 'react';",
    "import './index.css';",
    '',
    "type Category = 'All' | 'Mains' | 'Drinks' | 'Desserts';",
    "const menu = [{ name: 'Market bowl', category: 'Mains', price: 18 }, { name: 'Citrus spritz', category: 'Drinks', price: 9 }, { name: 'Chocolate tart', category: 'Desserts', price: 11 }];",
    ...appConstants(input, 'Restaurant experience', 'Explore the menu, filter dishes and reserve a table with clear feedback.'),
    '',
    'export default function App() {',
    "  const [category, setCategory] = useState<Category>('All');",
    "  const [name, setName] = useState('');",
    "  const [feedback, setFeedback] = useState('Pick a menu category or reserve a table.');",
    '  const filteredMenu = useMemo(() => menu.filter((item) => category === "All" || item.category === category), [category]);',
    '  function reserve(event: FormEvent) { event.preventDefault(); if (!name.trim()) { setFeedback("Add your name to reserve."); return; } setFeedback(`Table reserved for ${name.trim()}.`); setName(""); }',
    '  return <main className="min-h-screen bg-zinc-950 px-4 py-8 text-white sm:px-6 lg:px-8"><section className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-300">Generated by Huggy</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{appTitle}</h1><p className="mt-3 max-w-2xl text-zinc-300">{appSummary}</p><div className="mt-6 flex flex-wrap gap-2">{(["All", "Mains", "Drinks", "Desserts"] as Category[]).map((item) => <button key={item} className={category === item ? "rounded-full bg-white px-4 py-2 font-bold text-zinc-950" : "rounded-full border border-white/10 px-4 py-2 font-bold text-white"} type="button" onClick={() => setCategory(item)}>{item}</button>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{filteredMenu.map((item) => <article className="rounded-3xl border border-white/10 bg-white/10 p-5" key={item.name}><h2 className="text-xl font-bold">{item.name}</h2><p className="text-zinc-300">{item.category}</p><strong className="mt-3 block">${item.price}</strong><button className="mt-4 rounded-full bg-blue-400 px-4 py-2 font-bold text-zinc-950" type="button" onClick={() => setFeedback(`${item.name} selected.`)}>Choose</button></article>)}</div><form className="mt-6 grid gap-3 rounded-3xl bg-white/10 p-5 sm:grid-cols-[1fr_auto]" onSubmit={reserve}><input className="rounded-full border border-white/10 bg-white px-4 py-3 text-zinc-950" value={name} onChange={(event) => setName(event.target.value)} placeholder="Reservation name" /><button className="rounded-full bg-white px-5 py-3 font-bold text-zinc-950" type="submit">Reserve</button></form><p className="mt-4 rounded-2xl bg-blue-400/10 px-4 py-3 text-blue-100" role="status">{feedback}</p></section></main>;',
    '}',
    '',
  ].join('\n');
}

function portfolioApp(input: Required<GeneratedRescueInput>) {
  return genericApp(input, 'case studies, contact requests and a polished project gallery');
}

function genericApp(input: Required<GeneratedRescueInput>, focus = 'workflow, status and primary actions') {
  return [
    "import { FormEvent, useMemo, useState } from 'react';",
    "import './index.css';",
    '',
    "const seedItems = ['Intake', 'Review', 'Launch'];",
    ...appConstants(input, 'Product workspace', `A responsive web app with ${focus}.`),
    '',
    'export default function App() {',
    "  const [active, setActive] = useState('Intake');",
    "  const [query, setQuery] = useState('');",
    '  const [items, setItems] = useState(seedItems);',
    "  const [feedback, setFeedback] = useState('Workspace ready.');",
    '  const visible = useMemo(() => items.filter((item) => item.toLowerCase().includes(query.toLowerCase())), [items, query]);',
    '  function addItem(event: FormEvent) { event.preventDefault(); const clean = query.trim(); if (!clean) { setFeedback("Type something first."); return; } setItems((current) => Array.from(new Set([clean, ...current]))); setActive(clean); setFeedback(`${clean} added.`); setQuery(""); }',
    '  function reset() { if (!window.confirm("Reset the demo workflow?")) return; setItems(seedItems); setActive("Intake"); setFeedback("Workflow reset."); }',
    '  return (',
    '    <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-950 sm:px-6 lg:px-8">',
    '      <section className="mx-auto max-w-5xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">',
    '        <p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-600">Generated by Huggy</p>',
    '        <h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">{appTitle}</h1>',
    '        <p className="mt-3 max-w-2xl text-slate-600">{appSummary}</p>',
    '        <form className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto_auto]" onSubmit={addItem}><input className="rounded-full border border-slate-200 px-4 py-3" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search or add an item..." aria-label="Search or add" /><button className="rounded-full bg-slate-950 px-5 py-3 font-bold text-white" type="submit">Add</button><button className="rounded-full border border-slate-200 px-5 py-3 font-bold" type="button" onClick={reset}>Reset</button></form>',
    '        <div className="mt-6 grid gap-4 md:grid-cols-[220px_1fr]"><nav className="grid gap-2">{visible.length ? visible.map((item) => <button key={item} className={active === item ? "rounded-2xl bg-blue-600 px-4 py-3 text-left font-bold text-white" : "rounded-2xl border border-slate-200 px-4 py-3 text-left font-bold text-slate-700"} type="button" onClick={() => { setActive(item); setFeedback(`${item} selected.`); }}>{item}</button>) : <p className="rounded-2xl border border-dashed border-slate-300 p-4 text-slate-500">No matching items.</p>}</nav><article className="rounded-3xl bg-slate-100 p-6"><h2 className="text-2xl font-black">{active}</h2><p className="mt-3 text-slate-600">This section is interactive, responsive and ready to adapt to the requested product.</p><p className="mt-4 rounded-2xl bg-blue-50 px-4 py-3 text-blue-800" role="status">{feedback}</p></article></div>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}
