type PreviewFallbackFile = {
  path: string;
  content: string;
};

function escapeHtml(value: string) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function normalizeText(value: string) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

function inferKind(files: PreviewFallbackFile[], prompt = '') {
  const haystack = normalizeText([
    prompt,
    ...files.map(file => `${file.path}\n${file.content.slice(0, 4000)}`),
  ].join('\n'));

  if (/\b(todo|task|tache|kanban|checklist)\b/.test(haystack)) return 'todo';
  if (/\b(ecommerce|shop|cart|product|checkout|store|boutique|panier|produit)\b/.test(haystack)) return 'commerce';
  if (/\b(dashboard|analytics|crm|admin|metric|kpi)\b/.test(haystack)) return 'dashboard';
  if (/\b(booking|reservation|calendar|appointment|rendez-vous)\b/.test(haystack)) return 'booking';
  return 'app';
}

function fallbackTitle(projectName: string, kind: string) {
  if (projectName && !/^untitled|huggy app$/i.test(projectName.trim())) return projectName.trim();
  if (kind === 'todo') return 'Todo app';
  if (kind === 'commerce') return 'Product storefront';
  if (kind === 'dashboard') return 'Project dashboard';
  if (kind === 'booking') return 'Booking app';
  return 'Generated app';
}

function buildTodoFallback() {
  return [
    '<form class="huggy-preview-fallback-form" aria-label="Add task">',
    '  <input value="" placeholder="Add a task..." aria-label="Task title" />',
    '  <button type="button">Add</button>',
    '</form>',
    '<div class="huggy-preview-fallback-pills" aria-label="Task filters">',
    '  <span>All</span><span>Active</span><span>Completed</span>',
    '</div>',
    '<ul class="huggy-preview-fallback-list" aria-label="Task preview">',
    '  <li><span></span><strong>Plan the day</strong><small>Active</small></li>',
    '  <li><span></span><strong>Ship the first version</strong><small>Completed</small></li>',
    '</ul>',
  ].join('\n');
}

function buildDashboardFallback() {
  return [
    '<div class="huggy-preview-fallback-grid">',
    '  <article><strong>Revenue</strong><span>+18%</span></article>',
    '  <article><strong>Users</strong><span>2.4k</span></article>',
    '  <article><strong>Tasks</strong><span>37</span></article>',
    '</div>',
    '<div class="huggy-preview-fallback-chart" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>',
  ].join('\n');
}

function buildCommerceFallback() {
  return [
    '<div class="huggy-preview-fallback-grid">',
    '  <article><strong>Starter kit</strong><span>$29</span></article>',
    '  <article><strong>Pro bundle</strong><span>$79</span></article>',
    '  <article><strong>Launch pack</strong><span>$149</span></article>',
    '</div>',
    '<button type="button" class="huggy-preview-fallback-primary">View products</button>',
  ].join('\n');
}

function buildGenericFallback() {
  return [
    '<div class="huggy-preview-fallback-grid">',
    '  <article><strong>Responsive UI</strong><span>Desktop, tablet and mobile-ready layout.</span></article>',
    '  <article><strong>Interactive states</strong><span>Controls are prepared for real user flows.</span></article>',
    '  <article><strong>Deployable</strong><span>Ready for Huggy preview and publish.</span></article>',
    '</div>',
    '<button type="button" class="huggy-preview-fallback-primary">Open preview</button>',
  ].join('\n');
}

export function buildPreviewFallbackHtml(input: {
  projectName?: string;
  prompt?: string;
  files?: PreviewFallbackFile[];
}) {
  const files = input.files || [];
  const kind = inferKind(files, input.prompt || '');
  const title = fallbackTitle(input.projectName || '', kind);
  const body = kind === 'todo'
    ? buildTodoFallback()
    : kind === 'dashboard'
      ? buildDashboardFallback()
      : kind === 'commerce' || kind === 'booking'
        ? buildCommerceFallback()
        : buildGenericFallback();

  return [
    '<main data-huggy-preview-fallback="true" class="huggy-preview-fallback" aria-label="Generated app preview fallback">',
    '  <section class="huggy-preview-fallback-panel">',
    '    <p class="huggy-preview-fallback-kicker">Generated by Huggy</p>',
    `    <h1>${escapeHtml(title)}</h1>`,
    '    <p class="huggy-preview-fallback-copy">Your app is loading. If the live runtime is blocked, this recoverable preview keeps the page visible instead of showing a blank screen.</p>',
    body,
    '  </section>',
    '</main>',
  ].join('\n');
}

export const PREVIEW_FALLBACK_CSS = `
html,body,#root{min-height:100%;}body{margin:0;background:#fcfbf8;color:#1c1c1c;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}
.huggy-preview-fallback{min-height:100vh;display:grid;place-items:center;padding:clamp(22px,5vw,64px);background:radial-gradient(circle at 16% 12%,rgba(47,109,246,.12),transparent 31%),#fcfbf8;color:#1c1c1c;box-sizing:border-box;}
.huggy-preview-fallback-panel{width:min(100%,980px);border:1px solid #eceae4;border-radius:28px;background:rgba(255,255,255,.82);box-shadow:0 24px 80px rgba(28,28,28,.08);padding:clamp(26px,5vw,56px);}
.huggy-preview-fallback-kicker{margin:0 0 8px;color:#5f5f5d;font-size:12px;line-height:1.2;font-weight:850;letter-spacing:.12em;text-transform:uppercase;}
.huggy-preview-fallback h1{margin:0;color:#1c1c1c;font-size:clamp(32px,6vw,68px);line-height:.96;letter-spacing:0;font-weight:900;}
.huggy-preview-fallback-copy{max-width:680px;margin:16px 0 28px;color:#5f5f5d;font-size:clamp(16px,2vw,20px);line-height:1.55;}
.huggy-preview-fallback-form{display:flex;gap:10px;max-width:620px;margin:0 0 16px;}
.huggy-preview-fallback-form input{min-width:0;flex:1;height:48px;border:1px solid #eceae4;border-radius:16px;background:#fff;color:#1c1c1c;padding:0 16px;font:inherit;}
.huggy-preview-fallback-form button,.huggy-preview-fallback-primary{height:48px;border:0;border-radius:16px;background:#1c1c1c;color:#fff;padding:0 18px;font:800 14px/1 Inter,ui-sans-serif,system-ui;cursor:pointer;}
.huggy-preview-fallback-pills{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 16px;}
.huggy-preview-fallback-pills span{border:1px solid #eceae4;border-radius:999px;background:#f7f4ed;color:#1c1c1c;padding:8px 12px;font-size:13px;font-weight:750;}
.huggy-preview-fallback-list{display:grid;gap:10px;margin:0;padding:0;list-style:none;max-width:620px;}
.huggy-preview-fallback-list li{display:flex;align-items:center;gap:12px;border:1px solid #eceae4;border-radius:18px;background:#fff;padding:14px 16px;}
.huggy-preview-fallback-list li span{width:18px;height:18px;border-radius:999px;border:2px solid #2f6df6;}
.huggy-preview-fallback-list li small{margin-left:auto;color:#5f5f5d;font-weight:700;}
.huggy-preview-fallback-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:8px;}
.huggy-preview-fallback-grid article{min-height:118px;border:1px solid #eceae4;border-radius:20px;background:#fff;padding:20px;display:flex;flex-direction:column;justify-content:space-between;}
.huggy-preview-fallback-grid strong{font-size:18px;color:#1c1c1c;}.huggy-preview-fallback-grid span{color:#5f5f5d;line-height:1.45;}
.huggy-preview-fallback-chart{display:flex;align-items:end;gap:8px;height:140px;margin-top:16px;border:1px solid #eceae4;border-radius:20px;background:#fff;padding:18px;}
.huggy-preview-fallback-chart i{flex:1;border-radius:999px 999px 8px 8px;background:linear-gradient(180deg,#75c7ff,#2f6df6);min-height:30%;}.huggy-preview-fallback-chart i:nth-child(2){min-height:54%;}.huggy-preview-fallback-chart i:nth-child(3){min-height:78%;}.huggy-preview-fallback-chart i:nth-child(4){min-height:46%;}.huggy-preview-fallback-chart i:nth-child(5){min-height:68%;}
@media (max-width:720px){.huggy-preview-fallback{padding:18px}.huggy-preview-fallback-panel{border-radius:22px;padding:24px}.huggy-preview-fallback-grid{grid-template-columns:1fr}.huggy-preview-fallback-form{flex-direction:column}.huggy-preview-fallback-form button,.huggy-preview-fallback-primary{width:100%;}}
`;
