export type ProjectFile = {
  path: string;
  content: string;
  language?: string;
};

export type GeneratedApp = {
  files: ProjectFile[];
  summary: string;
  backendSchema: Record<string, unknown>;
  tests: string[];
};

const BLOCKED_SEGMENTS = new Set(['..', '.git', 'node_modules', '.env', 'dist', 'build']);
const ALLOWED_EXTENSIONS = new Set([
  'html',
  'css',
  'js',
  'jsx',
  'ts',
  'tsx',
  'json',
  'md',
  'svg'
]);

const DEFAULT_FILES: ProjectFile[] = [
  {
    path: 'index.html',
    language: 'html',
    content: '<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Huggy App</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>'
  },
  {
    path: 'src/main.tsx',
    language: 'tsx',
    content: "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport './style.css';\n\nfunction App() {\n  return <main className=\"app\"><section className=\"panel\"><p className=\"eyebrow\">Generated by Huggy</p><h1>Your fullstack app is ready.</h1><p>Use the chat to refine UI, database entities, and deployment settings.</p><button>Launch workflow</button></section></main>;\n}\n\ncreateRoot(document.getElementById('root')!).render(<App />);\n"
  },
  {
    path: 'src/style.css',
    language: 'css',
    content: ':root{font-family:Inter,system-ui,sans-serif;background:#070707;color:#f5f5f5}body{margin:0}.app{min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 30% 20%,rgba(99,102,241,.2),transparent 30%),#070707}.panel{width:min(720px,100%);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:40px;background:rgba(255,255,255,.05);box-shadow:0 24px 80px rgba(0,0,0,.35)}.eyebrow{text-transform:uppercase;letter-spacing:.12em;color:#9ca3af;font-size:12px}h1{font-size:clamp(36px,8vw,72px);line-height:.95;margin:0 0 18px}p{color:#d1d5db;line-height:1.7}button{border:0;border-radius:10px;padding:12px 18px;font-weight:700;background:#f5f5f5;color:#080808}@media(max-width:640px){.panel{padding:26px;border-radius:14px}}'
  },
  {
    path: 'package.json',
    language: 'json',
    content: '{\n  "name": "huggy-generated-app",\n  "private": true,\n  "version": "1.0.0",\n  "type": "module",\n  "scripts": { "build": "vite build", "dev": "vite --host 0.0.0.0" },\n  "dependencies": { "@vitejs/plugin-react": "latest", "vite": "latest", "typescript": "latest", "react": "latest", "react-dom": "latest" },\n  "devDependencies": {}\n}'
  }
];

export function starterFiles(prompt = 'Generated Huggy app'): ProjectFile[] {
  return DEFAULT_FILES.map((file) => ({
    ...file,
    content: file.path === 'src/main.tsx'
      ? file.content.replace('Your fullstack app is ready.', prompt.slice(0, 90) || 'Your fullstack app is ready.')
      : file.content
  }));
}

export function sanitizeGeneratedFiles(files: ProjectFile[]): ProjectFile[] {
  if (!Array.isArray(files) || files.length === 0) {
    throw new Error('Generated output did not include files.');
  }

  return files.map((file) => {
    const cleanPath = String(file.path || '').replace(/\\/g, '/').replace(/^\/+/, '').trim();
    const parts = cleanPath.split('/').filter(Boolean);
    const ext = cleanPath.split('.').pop()?.toLowerCase() || '';

    if (!cleanPath || parts.some((part) => BLOCKED_SEGMENTS.has(part)) || !ALLOWED_EXTENSIONS.has(ext)) {
      throw new Error(`Unsafe generated file path: ${file.path}`);
    }

    const content = String(file.content || '');
    if (/SUPABASE_SERVICE_ROLE_KEY|OPENROUTER_API_KEY|VERCEL_TOKEN|BEGIN PRIVATE KEY/i.test(content)) {
      throw new Error(`Generated file contains a forbidden secret reference: ${cleanPath}`);
    }

    return {
      path: cleanPath,
      content,
      language: file.language || ext
    };
  });
}

export function buildPreviewHtml(files: ProjectFile[]) {
  const fileMap = new Map(files.map((file) => [file.path, file.content]));
  const explicitHtml = fileMap.get('index.html');
  const css = [...fileMap.entries()]
    .filter(([path]) => path.endsWith('.css'))
    .map(([, content]) => content)
    .join('\n');
  const appText = fileMap.get('src/main.tsx') || fileMap.get('src/App.tsx') || '';
  const titleMatch = appText.match(/<h1[^>]*>(.*?)<\/h1>/s);
  const title = titleMatch?.[1]?.replace(/<[^>]+>/g, '') || 'Generated Huggy App';

  if (explicitHtml && !explicitHtml.includes('/src/main.tsx')) {
    return explicitHtml;
  }

  return `<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>${css || DEFAULT_FILES[2].content}</style>
</head>
<body>
  <main class="app">
    <section class="panel">
      <p class="eyebrow">Live sandbox preview</p>
      <h1>${escapeHtml(title)}</h1>
      <p>This preview is rendered in an isolated iframe. Deploy to Vercel when the build looks right.</p>
      <button>Ready to deploy</button>
    </section>
  </main>
</body>
</html>`;
}

export function vercelFiles(files: ProjectFile[]) {
  return sanitizeGeneratedFiles(files).map((file) => ({
    file: file.path,
    data: Buffer.from(file.content).toString('base64'),
    encoding: 'base64'
  }));
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
